services:
  client:
    image: client
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000 # SvelteKit dev server
      - 24678:24678 # Vite HMR port
    volumes:
      - ./:/app
      - /app/node_modules





# --- OLD ---

# version: '3.8'

# services:
#   sveltekit:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     volumes:
#       - .:/app
#     environment:
#       - NODE_ENV=development
#     command: ["yarn", "dev"]  # For development with hot-reloading

#   sveltekit-production:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"`
#     environment:
#       - NODE_ENV=production
#     command: ["yarn", "preview"]  # For production with the built app
